# Generated by Django 4.0 on 2021-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=69)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
